name: Deploy to Production S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production file
        run: |
          echo "API_BASE_URL_PROD exists: ${{ secrets.API_BASE_URL_PROD != '' }}"
          echo "GOOGLE_MAPS_API_KEY_PROD exists: ${{ secrets.GOOGLE_MAPS_API_KEY_PROD != '' }}"
          echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL_PROD }}" > .env.production
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY_PROD }}" >> .env.production

      - name: Build
        run: npm run build:prod

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://www.mymemory.co.kr --delete